[project]
name = 'invoicebtc-mvp'
description = 'InvoiceBTC escrow-backed invoice factoring MVP'
authors = []
telemetry = true
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-deposit'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'
[contracts.invoicebtc]
path = 'contracts/invoicebtc.clar'
clarity_version = 3
epoch = 3.0

[contracts.invoicebtc-v2]
path = 'contracts/invoicebtc.clar'
clarity_version = 3
epoch = 3.0

[contracts.invoicebtc-v3]
path = 'contracts/invoicebtc.clar'
clarity_version = 3
epoch = 3.0

[contracts.invoicebtc-v4]
path = 'contracts/invoicebtc.clar'
clarity_version = 3
epoch = 3.0

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
