[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "barrel film narrow gym jealous call soul patient wedding key turn wine anchor else license steel top balance come bounce miss bone actress trouble"
